services:
  - type: web
    name: minorproject2-backend
    runtime: python
    plan: free
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir backend --bind 0.0.0.0:$PORT run:app
    healthCheckPath: /api/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
