# -*- coding: utf-8 -*-
"""MinorProject2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kwk5dlJQiXSxIs_89SG89kEpfGe9aTVe

Block 0:Mount Drive and dataset download
"""

# CELL 1 — Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

import os
os.makedirs('/content/drive/MyDrive/CXR_Project', exist_ok=True)
print('✅ Google Drive mounted and project folder ready!')
DRIVE_DIR = '/content/drive/MyDrive/CXR_Project'

# CELL 2 — Download Dataset
import os, json

KAGGLE_USERNAME = 'snehasaha2005'
KAGGLE_KEY      = 'KGAT_e03525e714c5bbe12ad15a16c6949ecc'

os.makedirs('/root/.kaggle', exist_ok=True)
with open('/root/.kaggle/kaggle.json', 'w') as f:
    json.dump({'username': KAGGLE_USERNAME, 'key': KAGGLE_KEY}, f)
os.chmod('/root/.kaggle/kaggle.json', 0o600)

IMAGE_DIR = '/content/chest_xray_data/images-224/images-224'

if os.path.exists(IMAGE_DIR):
    print(f'✅ Dataset already exists! Images: {len(os.listdir(IMAGE_DIR))}')
else:
    print('⚠️ Dataset not found. Re-downloading...')
    !pip install -q kaggle
    !kaggle datasets download -d khanfashee/nih-chest-x-ray-14-224x224-resized --unzip -p /content/chest_xray_data
    print('✅ Dataset downloaded!')

"""BLOCK 1 — Chest X-ray Dataset Preparation"""

# CELL 3 — Install all libraries
!pip install -q grad-cam scikit-learn matplotlib seaborn pandas numpy Pillow tqdm huggingface_hub
print('✅ All libraries installed!')

# CELL 4 — Import all libraries
import os, json, random, warnings, re, time
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image
from tqdm import tqdm
from collections import Counter

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as transforms
from torchvision import models
from sklearn.metrics import roc_auc_score
from scipy.stats import chi2_contingency

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'✅ All libraries imported!')
print(f'✅ Device: {device}')
if torch.cuda.is_available():
    print(f'   GPU: {torch.cuda.get_device_name(0)}')
else:
    print('⚠️ WARNING: No GPU found! Go to Runtime → Change runtime type → T4 GPU')

# CELL 5 — Define all paths
IMAGE_DIR  = '/content/chest_xray_data/images-224/images-224'
CSV_PATH   = '/content/chest_xray_data/Data_Entry_2017.csv'
TRAIN_LIST = '/content/chest_xray_data/train_val_list_NIH.txt'
TEST_LIST  = '/content/chest_xray_data/test_list_NIH.txt'
DRIVE_DIR  = '/content/drive/MyDrive/CXR_Project'

df = pd.read_csv(CSV_PATH)
print(f'✅ CSV loaded: {df.shape[0]} rows')
print(f'\nColumns: {df.columns.tolist()}')
print(f'\nSample:')
print(df[['Image Index','Finding Labels','Patient Age','Patient Gender']].head(3).to_string())

# CELL 6 — One-hot encode 14 disease labels
DISEASE_LABELS = [
    'Atelectasis', 'Cardiomegaly', 'Effusion', 'Infiltration',
    'Mass', 'Nodule', 'Pneumonia', 'Pneumothorax',
    'Consolidation', 'Edema', 'Emphysema', 'Fibrosis',
    'Pleural_Thickening', 'Hernia'
]
NUM_CLASSES = len(DISEASE_LABELS)

for disease in DISEASE_LABELS:
    df[disease] = df['Finding Labels'].apply(lambda x: 1 if disease in str(x) else 0)

# Fix age — remove Y suffix like 058Y
def clean_age(val):
    try:
        return int(re.sub(r'[^0-9]', '', str(val)))
    except:
        return -1

def clean_age_capped(age):
    if age < 0 or age > 110:
        return -1
    return age

df['Patient Age']    = df['Patient Age'].apply(lambda x: clean_age_capped(clean_age(x)))
df['Patient Gender'] = df['Patient Gender'].fillna('Unknown')

# Age lookup for later use
age_lookup = dict(zip(df['Image Index'], df['Patient Age']))

print(f'✅ Labels encoded for {NUM_CLASSES} disease classes')
print(f'\nDisease distribution:')
dist = df[DISEASE_LABELS].sum().sort_values(ascending=False)
for d, c in dist.items():
    print(f'   {d:<22}: {c:>6} ({100*c/len(df):.1f}%)')

# CELL 7 — Train/Val/Test split (IMPROVED: 40K train for better AUC)
with open(TRAIN_LIST) as f:
    train_val_ids = set(x.strip() for x in f.readlines())
with open(TEST_LIST) as f:
    test_ids = set(x.strip() for x in f.readlines())

train_val_df = df[df['Image Index'].isin(train_val_ids)].reset_index(drop=True)
test_df      = df[df['Image Index'].isin(test_ids)].reset_index(drop=True)

val_size = int(0.1 * len(train_val_df))
val_df   = train_val_df[:val_size].reset_index(drop=True)
train_df = train_val_df[val_size:].reset_index(drop=True)

# IMPROVED: Use 40K training samples instead of 20K for better AUC
train_df = train_df.sample(n=40000, random_state=42).reset_index(drop=True)
val_df   = val_df.sample(n=5000,   random_state=42).reset_index(drop=True)
test_df  = test_df.sample(n=5000,  random_state=42).reset_index(drop=True)

print(f'✅ Split complete (IMPROVED - larger dataset):')
print(f'   Train : {len(train_df)} images')
print(f'   Val   : {len(val_df)} images')
print(f'   Test  : {len(test_df)} images')

# CELL 8 — Custom Dataset Class (IMPROVED transforms)
train_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(15),
    transforms.ColorJitter(brightness=0.3, contrast=0.3, saturation=0.1),
    transforms.RandomAffine(degrees=0, translate=(0.05, 0.05)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

val_test_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

class ChestXrayDataset(Dataset):
    def __init__(self, dataframe, image_dir, transform=None):
        self.df        = dataframe.reset_index(drop=True)
        self.image_dir = image_dir
        self.transform = transform

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row      = self.df.iloc[idx]
        img_path = os.path.join(self.image_dir, row['Image Index'])
        image    = Image.open(img_path).convert('RGB')
        if self.transform:
            image = self.transform(image)
        labels = torch.tensor([row[d] for d in DISEASE_LABELS], dtype=torch.float32)
        meta = {
            'image_id'  : row['Image Index'],
            'patient_id': str(row.get('Patient ID', 'unknown')),
            'age'       : int(row['Patient Age']),
            'gender'    : str(row['Patient Gender']),
        }
        return image, labels, meta

print('✅ Dataset class defined with improved augmentation!')

# CELL 9 — Create DataLoaders
train_dataset = ChestXrayDataset(train_df, IMAGE_DIR, train_transform)
val_dataset   = ChestXrayDataset(val_df,   IMAGE_DIR, val_test_transform)
test_dataset  = ChestXrayDataset(test_df,  IMAGE_DIR, val_test_transform)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True,  num_workers=2, pin_memory=True)
val_loader   = DataLoader(val_dataset,   batch_size=32, shuffle=False, num_workers=2, pin_memory=True)
test_loader  = DataLoader(test_dataset,  batch_size=32, shuffle=False, num_workers=2, pin_memory=True)

print(f'✅ DataLoaders ready:')
print(f'   Train batches : {len(train_loader)}')
print(f'   Val batches   : {len(val_loader)}')
print(f'   Test batches  : {len(test_loader)}')

# CELL 10 — Visualize 10 sample images
fig, axes = plt.subplots(2, 5, figsize=(20, 8))
fig.suptitle('Sample Chest X-ray Images — NIH Chest X-ray14', fontsize=14, fontweight='bold')

for i, ax in enumerate(axes.flat):
    row      = train_df.iloc[i]
    img_path = os.path.join(IMAGE_DIR, row['Image Index'])
    img      = Image.open(img_path).convert('RGB')
    diseases = [d for d in DISEASE_LABELS if row[d] == 1]
    label    = ', '.join(diseases) if diseases else 'No Finding'
    ax.imshow(img, cmap='gray')
    ax.set_title(f'{label}\n{row["Patient Gender"]}, Age {row["Patient Age"]}', fontsize=8, color='darkred')
    ax.axis('off')

plt.tight_layout()
plt.savefig('/content/sample_images.png', dpi=120, bbox_inches='tight')
plt.show()
print('✅ Sample images visualized!')

# CELL 11 — Save Block 1 to Drive
import shutil
train_df.to_csv(f'{DRIVE_DIR}/train_df.csv', index=False)
val_df.to_csv(f'{DRIVE_DIR}/val_df.csv',     index=False)
test_df.to_csv(f'{DRIVE_DIR}/test_df.csv',   index=False)
shutil.copy('/content/sample_images.png', f'{DRIVE_DIR}/sample_images.png')
print('✅ Block 1 complete and saved to Google Drive!')
print('   ➡️  Ready for Block 2 — Model Training')

"""BLOCK 2 — Medical Image Classification Model (DenseNet121)"""

# Cell 1 — Build DenseNet121 model
def build_densenet121(num_classes=14):
    model = models.densenet121(weights='IMAGENET1K_V1')

    # Replace final classifier for 14 disease classes
    in_features = model.classifier.in_features
    model.classifier = nn.Sequential(
        nn.Linear(in_features, 512),
        nn.ReLU(),
        nn.Dropout(0.3),
        nn.Linear(512, num_classes)
    )
    return model

model = build_densenet121(num_classes=NUM_CLASSES).to(device)

total_params   = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)

print(f"✅ DenseNet121 built successfully!")
print(f"   Total parameters     : {total_params:,}")
print(f"   Trainable parameters : {trainable_params:,}")
print(f"   Output classes       : {NUM_CLASSES}")

# Cell 2 — Define training function
def train_model(model, train_loader, val_loader, num_epochs=5, lr=1e-4):

    criterion = nn.BCEWithLogitsLoss()
    optimizer = optim.Adam(model.parameters(), lr=lr, weight_decay=1e-5)
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, mode='min', patience=2, factor=0.5
    )

    history        = {'train_loss': [], 'val_loss': [], 'val_auc': []}
    best_val_loss  = float('inf')

    for epoch in range(num_epochs):
        # ── Training ──
        model.train()
        train_loss = 0.0

        for images, labels, _ in tqdm(train_loader,
                                       desc=f'Epoch {epoch+1}/{num_epochs} [Train]'):
            images = images.to(device)
            labels = labels.to(device)

            optimizer.zero_grad()
            outputs = model(images)
            loss    = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
            train_loss += loss.item()

        avg_train_loss = train_loss / len(train_loader)

        # ── Validation ──
        model.eval()
        val_loss   = 0.0
        all_preds  = []
        all_labels = []

        with torch.no_grad():
            for images, labels, _ in tqdm(val_loader,
                                           desc=f'Epoch {epoch+1}/{num_epochs} [Val]'):
                images = images.to(device)
                labels = labels.to(device)

                outputs  = model(images)
                loss     = criterion(outputs, labels)
                val_loss += loss.item()

                preds = torch.sigmoid(outputs).cpu().numpy()
                all_preds.append(preds)
                all_labels.append(labels.cpu().numpy())

        avg_val_loss = val_loss / len(val_loader)

        all_preds  = np.vstack(all_preds)
        all_labels = np.vstack(all_labels)

        # Compute mean AUC across all 14 classes
        aucs = []
        for i in range(NUM_CLASSES):
            if len(np.unique(all_labels[:, i])) > 1:
                aucs.append(roc_auc_score(all_labels[:, i], all_preds[:, i]))
        mean_auc = np.mean(aucs) if aucs else 0.0

        scheduler.step(avg_val_loss)

        history['train_loss'].append(avg_train_loss)
        history['val_loss'].append(avg_val_loss)
        history['val_auc'].append(mean_auc)

        print(f"\n📊 Epoch {epoch+1:02d} Summary:")
        print(f"   Train Loss : {avg_train_loss:.4f}")
        print(f"   Val Loss   : {avg_val_loss:.4f}")
        print(f"   Mean AUC   : {mean_auc:.4f}")

        # Save best model
        if avg_val_loss < best_val_loss:
            best_val_loss = avg_val_loss
            torch.save(model.state_dict(), '/content/best_cxr_model.pth')
            print(f"   💾 Best model saved!")

    print(f"\n✅ Training complete! Best Val Loss: {best_val_loss:.4f}")
    return history

print("✅ Training function defined!")

print("🚀 Starting Training...")
print(f"   Epochs     : 5")
print(f"   Batch size : 16")
print(f"   Device     : {device}")
print("-" * 40)

history = train_model(
    model,
    train_loader,
    val_loader,
    num_epochs=5,
    lr=1e-4
)

# Cell 4 — Plot training curves
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle('DenseNet121 Training Curves', fontsize=14, fontweight='bold')

# Loss curve
axes[0].plot(history['train_loss'], label='Train Loss',
             color='steelblue', marker='o')
axes[0].plot(history['val_loss'],   label='Val Loss',
             color='tomato',    marker='o')
axes[0].set_title('Loss per Epoch')
axes[0].set_xlabel('Epoch')
axes[0].set_ylabel('BCE Loss')
axes[0].legend()
axes[0].grid(True, alpha=0.3)

# AUC curve
axes[1].plot(history['val_auc'], label='Val Mean AUC',
             color='seagreen', marker='o')
axes[1].set_title('Validation Mean AUC per Epoch')
axes[1].set_xlabel('Epoch')
axes[1].set_ylabel('AUC')
axes[1].legend()
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('/content/training_curves.png', dpi=120, bbox_inches='tight')
plt.show()
print("✅ Training curves saved!")

# Cell 5 — Save model and history to Google Drive
import shutil, json

# Save model weights
shutil.copy('/content/best_cxr_model.pth',
            f'{DRIVE_DIR}/best_cxr_model.pth')

# Save training history
with open('/content/training_history.json', 'w') as f:
    json.dump(history, f)
shutil.copy('/content/training_history.json',
            f'{DRIVE_DIR}/training_history.json')

# Save training curves plot
shutil.copy('/content/training_curves.png',
            f'{DRIVE_DIR}/training_curves.png')

print("✅ Block 2 complete and saved to Google Drive!")
print("   Model     → best_cxr_model.pth")
print("   History   → training_history.json")
print("   Curves    → training_curves.png")
print("\n   ➡️  Ready for Block 3 — Misclassification Detection")

"""BLOCK 3 — Misclassification Detection Module"""

# CELL 17 — Load best model
model.load_state_dict(torch.load('/content/best_cxr_model.pth', map_location=device))
model.eval()
print('✅ Best model loaded for inference!')

# CELL 18 — Run inference and detect misclassifications
THRESHOLD     = 0.5
all_results   = []
misclassified = []

print('🔍 Running inference on test set...')

with torch.no_grad():
    for images, labels, metas in tqdm(test_loader, desc='Inference'):
        images    = images.to(device)
        outputs   = model(images)
        probs     = torch.sigmoid(outputs).cpu().numpy()
        preds_bin = (probs >= THRESHOLD).astype(int)
        labels_np = labels.numpy().astype(int)

        for i in range(len(images)):
            true_diseases   = [DISEASE_LABELS[j] for j in range(NUM_CLASSES) if labels_np[i][j] == 1]
            pred_diseases   = [DISEASE_LABELS[j] for j in range(NUM_CLASSES) if preds_bin[i][j] == 1]
            true_set        = set(true_diseases)
            pred_set        = set(pred_diseases)
            false_positives = list(pred_set - true_set)
            false_negatives = list(true_set - pred_set)
            is_correct      = (true_set == pred_set)

            record = {
                'image_id'       : metas['image_id'][i],
                'patient_id'     : metas['patient_id'][i],
                'age'            : int(metas['age'][i]),
                'gender'         : metas['gender'][i],
                'true_labels'    : true_diseases,
                'pred_labels'    : pred_diseases,
                'false_positives': false_positives,
                'false_negatives': false_negatives,
                'confidence'     : {DISEASE_LABELS[j]: round(float(probs[i][j]), 4) for j in range(NUM_CLASSES)},
                'is_correct'     : is_correct
            }
            all_results.append(record)
            if not is_correct:
                misclassified.append(record)

# Fix ages using correct lookup
for r in misclassified:
    r['age'] = age_lookup.get(r['image_id'], -1)
    if r['age'] < 0 or r['age'] > 110:
        r['age'] = -1

total    = len(all_results)
n_errors = len(misclassified)
print(f'\n✅ Inference complete!')
print(f'   Total test samples  : {total}')
print(f'   Correctly classified: {total - n_errors} ({100*(total-n_errors)/total:.1f}%)')
print(f'   Misclassified       : {n_errors} ({100*n_errors/total:.1f}%)')

# CELL 19 — Analyze misclassification types
fp_only = [r for r in misclassified if r['false_positives'] and not r['false_negatives']]
fn_only = [r for r in misclassified if r['false_negatives'] and not r['false_positives']]
both    = [r for r in misclassified if r['false_positives'] and r['false_negatives']]

print(f'📊 Misclassification Breakdown:')
print(f'   False Positives only : {len(fp_only)}')
print(f'   False Negatives only : {len(fn_only)}')
print(f'   Both FP and FN       : {len(both)}')

fn_counter = {}
fp_counter = {}
for r in misclassified:
    for d in r['false_negatives']:
        fn_counter[d] = fn_counter.get(d, 0) + 1
    for d in r['false_positives']:
        fp_counter[d] = fp_counter.get(d, 0) + 1

print(f'\n📋 Top Missed Diseases (False Negatives):')
for d, c in sorted(fn_counter.items(), key=lambda x: -x[1])[:5]:
    print(f'   {d:<22}: {c}')
print(f'\n📋 Top Over-predicted Diseases (False Positives):')
for d, c in sorted(fp_counter.items(), key=lambda x: -x[1])[:5]:
    print(f'   {d:<22}: {c}')

# CELL 20 — Visualize misclassification distribution
fig, axes = plt.subplots(1, 2, figsize=(16, 6))
fig.suptitle('Misclassification Detection Analysis', fontsize=14, fontweight='bold')

if fn_counter:
    sorted_fn = sorted(fn_counter.items(), key=lambda x: -x[1])
    fn_d, fn_v = zip(*sorted_fn)
    axes[0].barh(fn_d, fn_v, color='tomato')
    axes[0].set_title('False Negatives per Disease (Missed by Model)', fontsize=12)
    axes[0].set_xlabel('Count')
    axes[0].invert_yaxis()

if fp_counter:
    sorted_fp = sorted(fp_counter.items(), key=lambda x: -x[1])
    fp_d, fp_v = zip(*sorted_fp)
    axes[1].barh(fp_d, fp_v, color='steelblue')
    axes[1].set_title('False Positives per Disease (Over-predicted)', fontsize=12)
    axes[1].set_xlabel('Count')
    axes[1].invert_yaxis()

plt.tight_layout()
plt.savefig('/content/misclassification_analysis.png', dpi=120, bbox_inches='tight')
plt.show()
print('✅ Misclassification chart saved!')

# CELL 21 — Save Block 3 to Drive
import shutil
with open('/content/misclassified_records.json', 'w') as f:
    json.dump(misclassified, f, indent=2)

misc_df = pd.DataFrame([{
    'image_id'       : r['image_id'],
    'age'            : r['age'],
    'gender'         : r['gender'],
    'true_labels'    : ', '.join(r['true_labels'])     or 'No Finding',
    'pred_labels'    : ', '.join(r['pred_labels'])     or 'No Finding',
    'false_positives': ', '.join(r['false_positives']) or 'None',
    'false_negatives': ', '.join(r['false_negatives']) or 'None',
} for r in misclassified])
misc_df.to_csv('/content/misclassified_records.csv', index=False)

shutil.copy('/content/misclassified_records.json', f'{DRIVE_DIR}/misclassified_records.json')
shutil.copy('/content/misclassified_records.csv',  f'{DRIVE_DIR}/misclassified_records.csv')
shutil.copy('/content/misclassification_analysis.png', f'{DRIVE_DIR}/misclassification_analysis.png')
print(f'✅ Block 3 complete and saved to Google Drive!')
print(f'   Total misclassified records: {len(misclassified)}')
print(f'   ➡️  Ready for Block 4 — Structured Error Data Generation')

"""BLOCK 4 — Structured Error Data Generation"""

# CELL 22 — Age group helper + structured prompts
def get_age_group(age):
    if age < 0:    return 'Unknown'
    elif age < 18: return 'Child (<18)'
    elif age < 40: return 'Young Adult (18-40)'
    elif age < 65: return 'Middle-aged (40-65)'
    else:          return 'Elderly (65+)'

def format_error_prompt(record):
    true_str  = ', '.join(record['true_labels'])    or 'No Finding'
    pred_str  = ', '.join(record['pred_labels'])    or 'No Finding'
    fp_str    = ', '.join(record['false_positives']) or 'None'
    fn_str    = ', '.join(record['false_negatives']) or 'None'
    top3_conf = sorted(record['confidence'].items(), key=lambda x: x[1], reverse=True)[:3]
    conf_str  = ', '.join(f'{d}: {v:.2f}' for d, v in top3_conf)
    age_group = get_age_group(record['age'])

    prompt = f"""You are a medical AI auditing assistant analyzing a chest X-ray misclassification.

PATIENT INFORMATION:
- Image ID      : {record['image_id']}
- Patient Age   : {record['age']} ({age_group})
- Patient Gender: {record['gender']}

CLASSIFICATION RESULT:
- True Diagnosis       : {true_str}
- Model Prediction     : {pred_str}
- False Positives      : {fp_str}
- False Negatives      : {fn_str}
- Top Confidence Scores: {conf_str}

Respond ONLY in valid JSON with these exact keys:
{{"ERROR_TYPE": "one of [False Positive, False Negative, Subtle Pathology Error, Overlapping Feature Confusion, Label Inconsistency, Demographic Bias]", "REASONING": "2-3 sentences", "BIAS_INDICATOR": "Yes or No with explanation", "SEVERITY": "Low or Medium or High", "RECOMMENDATION": "one actionable suggestion"}}"""
    return prompt

structured_prompts = [format_error_prompt(r) for r in misclassified]
print(f'✅ Structured prompts generated: {len(structured_prompts)}')

# CELL 23 — Preview structured data
preview_df = pd.DataFrame([{
    'image_id'       : r['image_id'],
    'age'            : r['age'],
    'age_group'      : get_age_group(r['age']),
    'gender'         : r['gender'],
    'true_labels'    : ', '.join(r['true_labels'])    or 'No Finding',
    'pred_labels'    : ', '.join(r['pred_labels'])    or 'No Finding',
    'false_positives': ', '.join(r['false_positives']) or 'None',
    'false_negatives': ', '.join(r['false_negatives']) or 'None',
    'top_confidence' : max(r['confidence'].values()),
    'error_category' : ('False Positive' if r['false_positives'] and not r['false_negatives']
                        else 'False Negative' if r['false_negatives'] and not r['false_positives']
                        else 'Both FP+FN')
} for r in misclassified])

print(f'✅ Structured error DataFrame: {preview_df.shape}')
print(preview_df[['image_id','true_labels','pred_labels','error_category','age_group','gender']].head(5).to_string())

# CELL 24 — Visualize error category distribution
fig, axes = plt.subplots(3, 1, figsize=(10, 20)) # Changed to 3 rows, 1 column, adjusted figsize
fig.suptitle('Structured Error Data — Category Overview', fontsize=14, fontweight='bold')

cat_counts = preview_df['error_category'].value_counts()
axes[0].bar(cat_counts.index, cat_counts.values, color=['tomato','steelblue','orange'])
axes[0].set_title('Error Category Distribution')
axes[0].set_ylabel('Count')
for i, v in enumerate(cat_counts.values):
    axes[0].text(i, v + 5, str(v), ha='center', fontsize=11)

age_counts = preview_df['age_group'].value_counts()
axes[1].pie(age_counts.values, labels=age_counts.index, autopct='%1.1f%%', startangle=90, pctdistance=1.2, labeldistance=1.3) # Increased pctdistance and labeldistance for clarity
axes[1].set_title('Misclassifications by Age Group')

gen_counts = preview_df['gender'].value_counts()
axes[2].bar(gen_counts.index, gen_counts.values, color=['#3498db','#e91e8c'], width=0.4)
axes[2].set_title('Misclassifications by Gender')
axes[2].set_ylabel('Count')

# Adjust layout to make space for the title and provide padding between subplots
plt.subplots_adjust(top=0.92, hspace=0.6) # Adjusted top margin and hspace for vertical layout
plt.savefig('/content/structured_error_overview.png', dpi=120, bbox_inches='tight')
plt.show()

import shutil
preview_df.to_csv('/content/structured_error_data.csv', index=False)
shutil.copy('/content/structured_error_data.csv',       f'{DRIVE_DIR}/structured_error_data.csv')
shutil.copy('/content/structured_error_overview.png',   f'{DRIVE_DIR}/structured_error_overview.png')
print(f'✅ Block 4 complete! Records: {len(preview_df)}, Prompts: {len(structured_prompts)}')
print('   ➡️  Ready for Block 5 — LLM-Based Error Reasoning')

"""BLOCK 5 — LLM-Based Error Reasoning Module"""

!pip install transformers accelerate bitsandbytes

from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

model_name = "mistralai/Mistral-7B-Instruct-v0.2"

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map="auto",
    torch_dtype=torch.float16
)

prompt = "Reply only with JSON: {\"status\":\"working\"}"

inputs = tokenizer(prompt, return_tensors="pt").to("cuda")

outputs = model.generate(
    **inputs,
    max_new_tokens=50
)

print(tokenizer.decode(outputs[0], skip_special_tokens=True))

# CELL 27 — Local LLM query function (using loaded Mistral model)

import json, re, torch

def query_llm(prompt, retries=2):

    formatted_prompt = f"[INST] {prompt} [/INST]"

    inputs = tokenizer(formatted_prompt, return_tensors="pt").to("cuda")

    outputs = model.generate(
        **inputs,
        max_new_tokens=350,
        temperature=0.2
    )

    response = tokenizer.decode(outputs[0], skip_special_tokens=True)

    # Remove prompt from response
    response = response.replace(formatted_prompt, "").strip()

    # Try to extract JSON
    try:
        return json.loads(response)
    except:
        match = re.search(r'\{.*?\}', response, re.DOTALL)
        if match:
            try:
                return json.loads(match.group())
            except:
                pass

    return {
        "ERROR_TYPE": "Unknown",
        "REASONING": response[:200],
        "BIAS_INDICATOR": "Unknown",
        "SEVERITY": "Unknown",
        "RECOMMENDATION": "Manual review needed"
    }

print("✅ Local Mistral LLM query function ready!")

# CELL 26 — Rule-based fallback (in case LLM has issues)
def rule_based_llm_analysis(record):

    true_labels = record['true_labels'] if isinstance(record['true_labels'], list) else record['true_labels'].split(', ')
    fp          = record['false_positives'] if isinstance(record['false_positives'], list) else record['false_positives'].split(', ')
    fn          = record['false_negatives'] if isinstance(record['false_negatives'], list) else record['false_negatives'].split(', ')
    age         = record['age']
    gender      = record['gender']

    fp_clean = [x for x in fp if x and x != 'None']
    fn_clean = [x for x in fn if x and x != 'None']

    OVERLAPPING_PAIRS = [
        ('Infiltration','Consolidation'),
        ('Effusion','Edema'),
        ('Atelectasis','Consolidation'),
        ('Mass','Nodule'),
        ('Emphysema','Pneumothorax'),
        ('Pleural_Thickening','Effusion')
    ]

    if fp_clean and not fn_clean:
        error_type = 'False Positive'
    elif fp_clean and fn_clean:
        pair_found = any((a in fn_clean and b in fp_clean) or (b in fn_clean and a in fp_clean) for a, b in OVERLAPPING_PAIRS)
        error_type = 'Overlapping Feature Confusion' if pair_found else 'Subtle Pathology Error'
    elif fn_clean:
        subtle     = ['Nodule', 'Mass', 'Fibrosis', 'Pleural_Thickening', 'Hernia']
        error_type = 'Subtle Pathology Error' if any(d in fn_clean for d in subtle) else 'False Negative'
    else:
        error_type = 'False Negative'

    high_risk   = ['Pneumothorax', 'Pneumonia', 'Edema', 'Mass', 'Cardiomegaly']
    medium_risk = ['Effusion', 'Consolidation', 'Atelectasis', 'Infiltration']
    all_missed  = fn_clean + fp_clean

    severity = ('High' if any(d in all_missed for d in high_risk)
                else 'Medium' if any(d in all_missed for d in medium_risk)
                else 'Low')

    bias = 'No'
    if age > 0 and (age < 18 or age > 75):
        bias = f'Yes — age group ({age}y) may be underrepresented'
    elif gender == 'F' and any(d in all_missed for d in ['Mass', 'Cardiomegaly']):
        bias = 'Yes — gender-related pathology differences possible'

    missed_str = ', '.join(fn_clean) if fn_clean else 'none'
    over_str   = ', '.join(fp_clean) if fp_clean else 'none'

    reasoning  = f'The model missed {missed_str} and over-predicted {over_str}.'

    return {
        'ERROR_TYPE': error_type,
        'REASONING': reasoning,
        'BIAS_INDICATOR': bias,
        'SEVERITY': severity,
        'RECOMMENDATION': 'Review training data quality.'
    }

print("✅ Rule-based fallback function defined!")

# CELL 28 — Run LLM analysis on 200 records

SAMPLE_SIZE    = 200
sample_records = misclassified[:SAMPLE_SIZE]
sample_prompts = structured_prompts[:SAMPLE_SIZE]

llm_results = []
failed      = 0

print(f'🤖 Running Local Mistral-7B on {SAMPLE_SIZE} records...\n')

for i, (record, prompt) in enumerate(zip(sample_records, sample_prompts)):

    response = query_llm(prompt)

    # If LLM fails, use rule-based fallback
    if response.get('ERROR_TYPE') in ['API Error', 'Unknown']:
        response = rule_based_llm_analysis(record)
        failed += 1

    llm_results.append({
        'image_id'       : record['image_id'],
        'patient_id'     : record['patient_id'],
        'age'            : record['age'],
        'age_group'      : get_age_group(record['age']),
        'gender'         : record['gender'],
        'true_labels'    : ', '.join(record['true_labels'])     or 'No Finding',
        'pred_labels'    : ', '.join(record['pred_labels'])     or 'No Finding',
        'false_positives': ', '.join(record['false_positives']) or 'None',
        'false_negatives': ', '.join(record['false_negatives']) or 'None',
        'ERROR_TYPE'     : response.get('ERROR_TYPE','Unknown'),
        'REASONING'      : response.get('REASONING',''),
        'BIAS_INDICATOR' : response.get('BIAS_INDICATOR','Unknown'),
        'SEVERITY'       : response.get('SEVERITY','Unknown'),
        'RECOMMENDATION' : response.get('RECOMMENDATION',''),
    })

    if (i + 1) % 20 == 0:
        print(f'   ✅ Processed {i+1}/{SAMPLE_SIZE}')

llm_df = pd.DataFrame(llm_results)

print('\n✅ LLM analysis complete!')
print(f'Total records: {len(llm_df)}')

print('\n📊 Error Type Distribution:')
print(llm_df['ERROR_TYPE'].value_counts())

print('\n📊 Severity Distribution:')
print(llm_df['SEVERITY'].value_counts())

# CELL 29 — Save Block 5
import shutil
llm_df.to_csv('/content/llm_analysis_results.csv', index=False)
shutil.copy('/content/llm_analysis_results.csv', f'{DRIVE_DIR}/llm_analysis_results.csv')
print('✅ Block 5 complete and saved!')
print('   ➡️  Ready for Block 6 — Structured Error Taxonomy')

"""BLOCK 6 — Structured Error Taxonomy Generation"""

# CELL 30 — Build taxonomy table
taxonomy_summary = llm_df.groupby('ERROR_TYPE').agg(
    Count           = ('image_id', 'count'),
    High_Severity   = ('SEVERITY', lambda x: (x == 'High').sum()),
    Medium_Severity = ('SEVERITY', lambda x: (x == 'Medium').sum()),
    Low_Severity    = ('SEVERITY', lambda x: (x == 'Low').sum()),
).reset_index()
taxonomy_summary['Percentage'] = (100 * taxonomy_summary['Count'] / taxonomy_summary['Count'].sum()).round(1)
taxonomy_summary = taxonomy_summary.sort_values('Count', ascending=False)

print('📋 STRUCTURED ERROR TAXONOMY TABLE')
print('=' * 65)
print(taxonomy_summary.to_string(index=False))
print('=' * 65)
print(f'Total analyzed: {taxonomy_summary["Count"].sum()} misclassifications')

# CELL 31 — Taxonomy visualization
fig, axes = plt.subplots(1, 3, figsize=(20, 6))
fig.suptitle('Structured Error Taxonomy — LLM Analysis\nNIH Chest X-ray14 DenseNet121', fontsize=14, fontweight='bold')

colors_e = ['#e74c3c', '#e67e22', '#3498db', '#2ecc71', '#9b59b6']
bars = axes[0].barh(taxonomy_summary['ERROR_TYPE'], taxonomy_summary['Count'], color=colors_e[:len(taxonomy_summary)])
axes[0].set_title('Error Type Distribution', fontsize=12)
axes[0].set_xlabel('Number of Cases')
axes[0].invert_yaxis()
for bar, pct in zip(bars, taxonomy_summary['Percentage']):
    axes[0].text(bar.get_width() + 0.3, bar.get_y() + bar.get_height()/2, f'{pct}%', va='center', fontsize=10)

sev_counts = llm_df['SEVERITY'].value_counts()
sev_order  = ['High', 'Medium', 'Low']
sev_vals   = [sev_counts.get(s, 0) for s in sev_order]
axes[1].pie(sev_vals, labels=sev_order, colors=['#e74c3c','#f39c12','#2ecc71'],
            autopct='%1.1f%%', startangle=90, wedgeprops={'edgecolor':'white','linewidth':2})
axes[1].set_title('Severity Distribution', fontsize=12)

pivot = llm_df.groupby(['ERROR_TYPE', 'SEVERITY']).size().unstack(fill_value=0)
for col in ['High', 'Medium', 'Low']:
    if col not in pivot.columns:
        pivot[col] = 0
pivot[['High','Medium','Low']].plot(kind='bar', stacked=True, ax=axes[2],
    color=['#e74c3c','#f39c12','#2ecc71'], edgecolor='white')
axes[2].set_title('Severity per Error Type', fontsize=12)
axes[2].tick_params(axis='x', rotation=30)

plt.tight_layout()
plt.savefig('/content/error_taxonomy.png', dpi=150, bbox_inches='tight')
plt.show()
print('✅ Error taxonomy chart saved!')

# CELL 32 — Disease-wise error breakdown
disease_error_map = {}
for _, row in llm_df.iterrows():
    fn_list = [x.strip() for x in str(row['false_negatives']).split(',') if x.strip() and x.strip() != 'None']
    fp_list = [x.strip() for x in str(row['false_positives']).split(',') if x.strip() and x.strip() != 'None']
    for d in fn_list + fp_list:
        if d not in disease_error_map:
            disease_error_map[d] = {'High': 0, 'Medium': 0, 'Low': 0, 'Total': 0}
        disease_error_map[d][row['SEVERITY']] += 1
        disease_error_map[d]['Total'] += 1

disease_df = pd.DataFrame(disease_error_map).T.sort_values('Total', ascending=False)
print('📊 Disease-wise Error Breakdown:')
print('=' * 55)
print(disease_df.to_string())

# Cell 4 — Disease confusion heatmap (which diseases get confused most)
fig, axes = plt.subplots(1, 2, figsize=(18, 7))
fig.suptitle('Disease-Level Error Pattern Analysis', fontsize=14, fontweight='bold')

# Chart 1: Disease error frequency
if len(disease_df) > 0:
    top_diseases = disease_df.head(10)
    x = range(len(top_diseases))
    width = 0.25

    axes[0].bar([i - width for i in x], top_diseases['High'],
                width, label='High', color='#e74c3c')
    axes[0].bar([i for i in x], top_diseases['Medium'],
                width, label='Medium', color='#f39c12')
    axes[0].bar([i + width for i in x], top_diseases['Low'],
                width, label='Low', color='#2ecc71')

    axes[0].set_xticks(x)
    axes[0].set_xticklabels(top_diseases.index, rotation=45, ha='right')
    axes[0].set_title('Error Severity by Disease Class', fontsize=12)
    axes[0].set_ylabel('Number of Errors')
    axes[0].legend()

# Chart 2: Top confused disease pairs
pair_counter = {}
for r in misclassified[:200]:
    fp_list = [x for x in r['false_positives'] if x]
    fn_list = [x for x in r['false_negatives'] if x]
    for fn_d in fn_list:
        for fp_d in fp_list:
            if fn_d != fp_d:
                pair = f"{fn_d} → {fp_d}"
                pair_counter[pair] = pair_counter.get(pair, 0) + 1

if pair_counter:
    top_pairs  = sorted(pair_counter.items(), key=lambda x: -x[1])[:8]
    pair_labels = [p[0] for p in top_pairs]
    pair_vals   = [p[1] for p in top_pairs]

    axes[1].barh(pair_labels[::-1], pair_vals[::-1],
                 color=plt.cm.Oranges(
                     [0.4 + 0.5 * v/max(pair_vals) for v in pair_vals[::-1]]
                 ))
    axes[1].set_title('Top Confused Disease Pairs\n(True → Predicted)', fontsize=12)
    axes[1].set_xlabel('Frequency')
else:
    axes[1].text(0.5, 0.5, 'No confusion pairs found\n(only false negatives)',
                 ha='center', va='center', fontsize=12,
                 transform=axes[1].transAxes)
    axes[1].set_title('Top Confused Disease Pairs', fontsize=12)

plt.tight_layout()
plt.savefig('/content/disease_error_breakdown.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ Disease error breakdown chart saved!")

# CELL 33 — Save Block 6
import shutil
taxonomy_summary.to_csv('/content/error_taxonomy_table.csv', index=False)
disease_df.to_csv('/content/disease_error_breakdown.csv')
shutil.copy('/content/error_taxonomy_table.csv',    f'{DRIVE_DIR}/error_taxonomy_table.csv')
shutil.copy('/content/disease_error_breakdown.csv', f'{DRIVE_DIR}/disease_error_breakdown.csv')
shutil.copy('/content/error_taxonomy.png',          f'{DRIVE_DIR}/error_taxonomy.png')
print('✅ Block 6 complete and saved!')
print('\nTaxonomy Summary:')
for _, row in taxonomy_summary.iterrows():
    print(f'   {row["ERROR_TYPE"]:<35} {row["Count"]:>3} cases ({row["Percentage"]}%)')
print('   ➡️  Ready for Block 7 — Dataset Bias Detection')

"""BLOCK 7 — Dataset Bias Detection"""

# CELL 34 — Gender and age bias analysis
print('=' * 55)
print('BIAS ANALYSIS — GENDER')
print('=' * 55)

gender_error = llm_df.groupby('gender').agg(
    Total           = ('image_id', 'count'),
    High_Severity   = ('SEVERITY', lambda x: (x=='High').sum()),
    Medium_Severity = ('SEVERITY', lambda x: (x=='Medium').sum()),
    Low_Severity    = ('SEVERITY', lambda x: (x=='Low').sum()),
).reset_index()
gender_error['High_%'] = (100 * gender_error['High_Severity'] / gender_error['Total']).round(1)
print(gender_error.to_string(index=False))

contingency_gender = pd.crosstab(llm_df['gender'], llm_df['SEVERITY'])
chi2, p_val, dof, _ = chi2_contingency(contingency_gender)
print(f'\n📊 Chi-square Test (Gender vs Severity):')
print(f'   Chi2={chi2:.3f} | p-value={p_val:.4f}')
print('   ⚠️  SIGNIFICANT gender bias!' if p_val < 0.05 else '   ✅ No significant gender bias (p >= 0.05)')

print('\n' + '=' * 55)
print('BIAS ANALYSIS — AGE GROUP')
print('=' * 55)

age_error = llm_df[llm_df['age'] > 0].groupby('age_group').agg(
    Total           = ('image_id', 'count'),
    High_Severity   = ('SEVERITY', lambda x: (x=='High').sum()),
    Medium_Severity = ('SEVERITY', lambda x: (x=='Medium').sum()),
    Low_Severity    = ('SEVERITY', lambda x: (x=='Low').sum()),
).reset_index()
age_error['High_%'] = (100 * age_error['High_Severity'] / age_error['Total']).round(1)
print(age_error.to_string(index=False))

contingency_age  = pd.crosstab(llm_df[llm_df['age']>0]['age_group'], llm_df[llm_df['age']>0]['SEVERITY'])
chi2_a, p_a, dof_a, _ = chi2_contingency(contingency_age)
print(f'\n📊 Chi-square Test (Age vs Severity):')
print(f'   Chi2={chi2_a:.3f} | p-value={p_a:.4f}')
print('   ⚠️  SIGNIFICANT age bias!' if p_a < 0.05 else '   ✅ No significant age bias (p >= 0.05)')

# CELL 35 — Bias visualization
fn_gender_rows = []
for _, row in llm_df.iterrows():
    fn_list = [x.strip() for x in str(row['false_negatives']).split(',') if x.strip() and x.strip() != 'None']
    for disease in fn_list:
        fn_gender_rows.append({'disease': disease, 'gender': row['gender'], 'severity': row['SEVERITY']})
fn_gender_df = pd.DataFrame(fn_gender_rows)

fig, axes = plt.subplots(2, 2, figsize=(18, 14))
fig.suptitle('Dataset Bias Detection — Demographic Analysis', fontsize=15, fontweight='bold')

sev_gender = llm_df.groupby(['gender','SEVERITY']).size().unstack(fill_value=0)
sev_order  = [s for s in ['High','Medium','Low'] if s in sev_gender.columns]
sev_gender[sev_order].plot(kind='bar', stacked=True, ax=axes[0][0], color=['#e74c3c','#f39c12','#2ecc71'], rot=0)
axes[0][0].set_title('Severity by Gender', fontsize=12)

valid_age = llm_df[llm_df['age'] > 0]
sev_age   = valid_age.groupby(['age_group','SEVERITY']).size().unstack(fill_value=0)
sev_order2 = [s for s in ['High','Medium','Low'] if s in sev_age.columns]
sev_age[sev_order2].plot(kind='bar', stacked=True, ax=axes[0][1], color=['#e74c3c','#f39c12','#2ecc71'], rot=20)
axes[0][1].set_title('Severity by Age Group', fontsize=12)

if not fn_gender_df.empty:
    high_fn = fn_gender_df[fn_gender_df['severity']=='High']
    if not high_fn.empty:
        dg = high_fn.groupby(['disease','gender']).size().unstack(fill_value=0)
        dg.plot(kind='barh', ax=axes[1][0], color=['#3498db','#e91e8c'])
        axes[1][0].set_title('High Severity FN by Disease & Gender', fontsize=12)

bias_counts = llm_df['BIAS_INDICATOR'].apply(lambda x: 'Bias Detected' if str(x).startswith('Yes') else 'No Bias').value_counts()
colors_b    = ['#e74c3c' if 'Bias' in k else '#2ecc71' for k in bias_counts.index]
axes[1][1].pie(bias_counts.values, labels=bias_counts.index, autopct='%1.1f%%', colors=colors_b, startangle=90)
axes[1][1].set_title('LLM Bias Indicator Summary', fontsize=12)

plt.tight_layout()
plt.savefig('/content/bias_detection.png', dpi=120, bbox_inches='tight')
plt.show()

total    = len(llm_df)
bias_yes = llm_df['BIAS_INDICATOR'].apply(lambda x: str(x).startswith('Yes')).sum()
print(f'\n✅ Bias Detection Summary:')
print(f'   Bias detected : {bias_yes} ({100*bias_yes/total:.1f}%)')
print(f'   No bias       : {total-bias_yes} ({100*(total-bias_yes)/total:.1f}%)')

print("=" * 55)
print("BIAS DETECTION SUMMARY REPORT")
print("=" * 55)

total      = len(llm_df)
bias_yes   = llm_df['BIAS_INDICATOR'].apply(
    lambda x: str(x).startswith('Yes')
).sum()
bias_no    = total - bias_yes

print(f"\nTotal records analyzed : {total}")
print(f"Bias detected          : {bias_yes} ({100*bias_yes/total:.1f}%)")
print(f"No bias                : {bias_no}  ({100*bias_no/total:.1f}%)")

print(f"\nGender breakdown:")
for g, cnt in llm_df['gender'].value_counts().items():
    high = ((llm_df['gender']==g) & (llm_df['SEVERITY']=='High')).sum()
    print(f"   {g}: {cnt} errors | High severity: {high} ({100*high/cnt:.1f}%)")

print(f"\nAge group breakdown:")
for ag, cnt in llm_df[llm_df['age']>0]['age_group'].value_counts().items():
    high = ((llm_df['age_group']==ag) & (llm_df['SEVERITY']=='High')).sum()
    print(f"   {ag}: {cnt} errors | High severity: {high} ({100*high/cnt:.1f}%)")

# CELL 36 — Save Block 7
import shutil
llm_df.to_csv('/content/llm_analysis_with_bias.csv', index=False)
shutil.copy('/content/bias_detection.png',          f'{DRIVE_DIR}/bias_detection.png')
shutil.copy('/content/llm_analysis_with_bias.csv',  f'{DRIVE_DIR}/llm_analysis_with_bias.csv')
print('✅ Block 7 complete and saved!')
print('   ➡️  Ready for Block 8 — Label Inconsistency Detection')

"""BLOCK 8 — Label Inconsistency Detection"""

# CELL 37 — Define disease keywords and report templates
DISEASE_KEYWORDS = {
    'Atelectasis'        : ['atelectasis', 'collapse', 'opacit', 'linear'],
    'Cardiomegaly'       : ['cardiomegaly', 'enlarged heart', 'cardiac enlargement'],
    'Effusion'           : ['effusion', 'pleural fluid', 'blunting'],
    'Infiltration'       : ['infiltration', 'infiltrate', 'opacity', 'haziness'],
    'Mass'               : ['mass', 'lesion', 'tumor', 'neoplasm'],
    'Nodule'             : ['nodule', 'nodular', 'granuloma'],
    'Pneumonia'          : ['pneumonia', 'consolidation', 'infection', 'opacity'],
    'Pneumothorax'       : ['pneumothorax', 'air', 'pleural'],
    'Consolidation'      : ['consolidation', 'opacification', 'airspace'],
    'Edema'              : ['edema', 'interstitial', 'vascular congestion'],
    'Emphysema'          : ['emphysema', 'hyperinflation', 'hyperlucen'],
    'Fibrosis'           : ['fibrosis', 'fibrotic', 'scarring', 'interstitial'],
    'Pleural_Thickening' : ['pleural thickening', 'pleural', 'thickening'],
    'Hernia'             : ['hernia', 'bowel', 'diaphragm']
}

REPORT_TEMPLATES = {
    'positive'  : [
        'There is a subtle {disease} present in the {location} lobe.',
        'Findings consistent with {disease} are noted.',
        'Evidence of {disease} observed on this radiograph.',
        '{disease} is identified in this study.',
        'The radiograph demonstrates findings suggestive of {disease}.',
    ],
    'negative'  : [
        'No acute cardiopulmonary abnormality. Lungs are clear.',
        'Clear lungs bilaterally. No pleural effusion or pneumothorax.',
        'No significant findings. Normal chest radiograph.',
        'Lungs appear clear without focal consolidation or effusion.',
    ],
    'ambiguous' : [
        'Mild increased interstitial markings, nonspecific.',
        'Possible subtle opacity in the right lower lobe, clinical correlation recommended.',
        'Borderline cardiac silhouette. Repeat imaging suggested.',
        'Cannot exclude early infiltrate given clinical presentation.',
    ]
}
LOCATIONS = ['right upper', 'right lower', 'left upper', 'left lower', 'bilateral']
print(f'✅ Keywords and templates defined! Diseases: {len(DISEASE_KEYWORDS)}')

# CELL 38 — Generate simulated reports + detect inconsistencies
random.seed(42)

def generate_simulated_report(true_labels):
    true_list = [x.strip() for x in str(true_labels).split(',') if x.strip() and x.strip() != 'No Finding']
    chance    = random.random()
    if not true_list:
        return random.choice(REPORT_TEMPLATES['negative']), 'negative'
    elif chance < 0.15:
        return random.choice(REPORT_TEMPLATES['negative']), 'inconsistent_negative'
    elif chance < 0.25:
        return random.choice(REPORT_TEMPLATES['ambiguous']), 'ambiguous'
    else:
        disease  = random.choice(true_list)
        template = random.choice(REPORT_TEMPLATES['positive'])
        location = random.choice(LOCATIONS)
        return template.format(disease=disease.lower(), location=location), 'positive'

def detect_inconsistency(true_labels_str, report_text):
    true_list      = [x.strip() for x in str(true_labels_str).split(',') if x.strip() and x.strip() != 'No Finding']
    report_lower   = report_text.lower()
    neg_markers    = ['no acute','clear lung','normal','no significant','no evidence','lungs are clear','no pleural','no focal','without focal']
    is_negative    = any(m in report_lower for m in neg_markers)
    inconsistencies = []
    confidence_sum  = 0.0
    for disease in true_list:
        keywords          = DISEASE_KEYWORDS.get(disease, [disease.lower()])
        disease_mentioned = any(k in report_lower for k in keywords)
        if not disease_mentioned and is_negative:
            inconsistencies.append(f"Label '{disease}' not supported by report")
            confidence_sum += 0.8
        elif not disease_mentioned:
            inconsistencies.append(f"Label '{disease}' not mentioned in report")
            confidence_sum += 0.4
    for disease, keywords in DISEASE_KEYWORDS.items():
        if disease not in true_list and any(k in report_lower for k in keywords) and not is_negative:
            inconsistencies.append(f"Report mentions '{disease}' but not in label")
            confidence_sum += 0.6
    inconsistent = len(inconsistencies) > 0
    confidence   = min(confidence_sum / max(len(true_list), 1), 1.0)
    explanation  = '; '.join(inconsistencies) if inconsistencies else 'Consistent'
    return inconsistent, round(confidence, 2), explanation

# Generate and detect
incons_results = []
for record in misclassified[:200]:
    true_labels      = ', '.join(record['true_labels']) or 'No Finding'
    pred_labels      = ', '.join(record['pred_labels']) or 'No Finding'
    report, rtype    = generate_simulated_report(true_labels)
    inc, conf, expl  = detect_inconsistency(true_labels, report)
    incons_results.append({'image_id': record['image_id'], 'true_labels': true_labels,
                           'pred_labels': pred_labels, 'report': report,
                           'report_type': rtype, 'inconsistent': inc,
                           'confidence': conf, 'explanation': expl})

incons_df        = pd.DataFrame(incons_results)
total_incons     = incons_df['inconsistent'].sum()
high_conf_incons = ((incons_df['inconsistent']) & (incons_df['confidence'] >= 0.7)).sum()

print(f'✅ Label inconsistency detection complete!')
print(f'   Total checked          : {len(incons_df)}')
print(f'   Inconsistencies found  : {total_incons} ({100*total_incons/len(incons_df):.1f}%)')
print(f'   High confidence (≥0.7) : {high_conf_incons} ({100*high_conf_incons/len(incons_df):.1f}%)')

import random
random.seed(42)

def generate_simulated_report(true_labels, pred_labels):
    """
    Generates a simulated radiology report for a sample.
    Intentionally introduces inconsistencies in ~20% of cases.
    """
    true_list = [x.strip() for x in str(true_labels).split(',')
                 if x.strip() and x.strip() != 'No Finding']

    # 20% chance of inconsistency — report contradicts label
    inconsistency_chance = random.random()

    if not true_list:
        report = random.choice(REPORT_TEMPLATES['negative'])
        report_type = 'negative'
    elif inconsistency_chance < 0.15:
        # Inconsistent — report says negative but label says positive
        report = random.choice(REPORT_TEMPLATES['negative'])
        report_type = 'inconsistent_negative'
    elif inconsistency_chance < 0.25:
        # Ambiguous report
        report = random.choice(REPORT_TEMPLATES['ambiguous'])
        report_type = 'ambiguous'
    else:
        # Consistent positive report
        disease = random.choice(true_list)
        template = random.choice(REPORT_TEMPLATES['positive'])
        location = random.choice(LOCATIONS)
        report   = template.format(
            disease=disease.lower(),
            location=location
        )
        report_type = 'positive'

    return report, report_type


# Generate reports for all misclassified samples
reports_data = []
for record in misclassified[:200]:
    true_labels = ', '.join(record['true_labels']) or 'No Finding'
    pred_labels = ', '.join(record['pred_labels']) or 'No Finding'
    report, rtype = generate_simulated_report(true_labels, pred_labels)

    reports_data.append({
        'image_id'   : record['image_id'],
        'true_labels': true_labels,
        'pred_labels': pred_labels,
        'report'     : report,
        'report_type': rtype
    })

reports_df = pd.DataFrame(reports_data)
print(f"✅ Simulated reports generated: {len(reports_df)}")
print(f"\nReport type distribution:")
print(reports_df['report_type'].value_counts().to_string())
print(f"\nSample reports:")
print(reports_df[['image_id','true_labels','report']].head(5).to_string())

# Cell 3 — Detect label inconsistencies
def detect_inconsistency(true_labels_str, report_text):
    """
    Checks if radiology report is consistent with assigned labels.
    Returns: inconsistent (bool), confidence (float), explanation (str)
    """
    true_list    = [x.strip() for x in str(true_labels_str).split(',')
                    if x.strip() and x.strip() != 'No Finding']
    report_lower = report_text.lower()

    # Negative report markers
    negative_markers = ['no acute', 'clear lung', 'normal', 'no significant',
                        'no evidence', 'lungs are clear', 'no pleural',
                        'no focal', 'without focal']
    report_is_negative = any(m in report_lower for m in negative_markers)

    inconsistencies = []
    confidence_sum  = 0.0

    for disease in true_list:
        keywords = DISEASE_KEYWORDS.get(disease, [disease.lower()])
        disease_mentioned = any(k in report_lower for k in keywords)

        if not disease_mentioned and report_is_negative:
            inconsistencies.append(
                f"Label '{disease}' not supported by report findings"
            )
            confidence_sum += 0.8
        elif not disease_mentioned and not report_is_negative:
            inconsistencies.append(
                f"Label '{disease}' not explicitly mentioned in report"
            )
            confidence_sum += 0.4

    # Check for diseases mentioned in report but NOT in labels
    for disease, keywords in DISEASE_KEYWORDS.items():
        if disease not in true_list:
            if any(k in report_lower for k in keywords) and not report_is_negative:
                inconsistencies.append(
                    f"Report mentions '{disease}' but it is not in the label"
                )
                confidence_sum += 0.6

    inconsistent  = len(inconsistencies) > 0
    confidence    = min(confidence_sum / max(len(true_list), 1), 1.0)
    explanation   = '; '.join(inconsistencies) if inconsistencies else 'Labels and report are consistent'

    return inconsistent, round(confidence, 2), explanation


# Run inconsistency detection on all samples
print("Running label inconsistency detection...")
incons_results = []

for _, row in reports_df.iterrows():
    inconsistent, confidence, explanation = detect_inconsistency(
        row['true_labels'], row['report']
    )
    incons_results.append({
        'image_id'      : row['image_id'],
        'true_labels'   : row['true_labels'],
        'report'        : row['report'],
        'report_type'   : row['report_type'],
        'inconsistent'  : inconsistent,
        'confidence'    : confidence,
        'explanation'   : explanation
    })

incons_df = pd.DataFrame(incons_results)

total_checked   = len(incons_df)
total_incons    = incons_df['inconsistent'].sum()
high_conf_incons = ((incons_df['inconsistent']) &
                    (incons_df['confidence'] >= 0.7)).sum()

print(f"\n✅ Label inconsistency detection complete!")
print(f"   Total checked              : {total_checked}")
print(f"   Inconsistencies found      : {total_incons} ({100*total_incons/total_checked:.1f}%)")
print(f"   High confidence (≥0.7)     : {high_conf_incons} ({100*high_conf_incons/total_checked:.1f}%)")
print(f"\nSample inconsistencies:")
print(incons_df[incons_df['inconsistent']==True][
    ['image_id','true_labels','explanation']
].head(5).to_string())

# CELL 39 — Visualize inconsistencies + save
fig, axes = plt.subplots(1, 3, figsize=(18, 6))
fig.suptitle('Label Inconsistency Detection Results', fontsize=14, fontweight='bold')

counts = incons_df['inconsistent'].value_counts()
axes[0].pie([counts.get(False,0), counts.get(True,0)], labels=['Consistent','Inconsistent'],
            autopct='%1.1f%%', colors=['#2ecc71','#e74c3c'], startangle=90)
axes[0].set_title('Label-Report Consistency', fontsize=12)

incons_only = incons_df[incons_df['inconsistent']==True]
if not incons_only.empty:
    axes[1].hist(incons_only['confidence'], bins=10, color='tomato', edgecolor='white')
    axes[1].axvline(x=0.7, color='red', linestyle='--', label='High confidence')
    axes[1].set_title('Inconsistency Confidence Distribution', fontsize=12)
    axes[1].legend()

rtype_counts = incons_df.groupby(['report_type','inconsistent']).size().unstack(fill_value=0)
rtype_counts.plot(kind='bar', ax=axes[2], color=['#2ecc71','#e74c3c'], rot=20)
axes[2].set_title('Inconsistency by Report Type', fontsize=12)

plt.tight_layout()
plt.savefig('/content/label_inconsistency.png', dpi=120, bbox_inches='tight')
plt.show()

disease_incons = {}
for _, row in incons_df[incons_df['inconsistent']==True].iterrows():
    for d in [x.strip() for x in str(row['true_labels']).split(',') if x.strip() and x.strip()!='No Finding']:
        disease_incons[d] = disease_incons.get(d, 0) + 1

print('\n📋 Disease-wise Inconsistency Breakdown:')
for d, c in sorted(disease_incons.items(), key=lambda x: -x[1]):
    print(f'   {d:<25}: {c}')

import shutil
incons_df.to_csv('/content/label_inconsistencies.csv', index=False)
shutil.copy('/content/label_inconsistencies.csv', f'{DRIVE_DIR}/label_inconsistencies.csv')
shutil.copy('/content/label_inconsistency.png',   f'{DRIVE_DIR}/label_inconsistency.png')
print(f'\n✅ Block 8 complete and saved!')
print('   ➡️  Ready for Block 9 — Dataset-Level Error Pattern Analysis')

"""BLOCK 9 — Dataset-Level Error Pattern Analysis"""

# CELL 40 — Confusion matrix + confused disease pairs
confusion_pairs = {}
for record in misclassified[:200]:
    fn_list = record['false_negatives'] if isinstance(record['false_negatives'], list) else [x.strip() for x in str(record['false_negatives']).split(',')]
    fp_list = record['false_positives'] if isinstance(record['false_positives'], list) else [x.strip() for x in str(record['false_positives']).split(',')]
    for fn in [x for x in fn_list if x and x!='None']:
        for fp in [x for x in fp_list if x and x!='None']:
            pair = tuple(sorted([fn, fp]))
            confusion_pairs[pair] = confusion_pairs.get(pair, 0) + 1

sorted_pairs = sorted(confusion_pairs.items(), key=lambda x: -x[1])
print('📋 Top Confused Disease Pairs:')
for (a, b), count in sorted_pairs[:10]:
    print(f'   {a:<25} ↔ {b:<25} : {count} times')

# Confusion matrix
top8        = ['Atelectasis','Cardiomegaly','Effusion','Infiltration','Mass','Nodule','Pneumonia','Pneumothorax']
conf_matrix = np.zeros((8, 8), dtype=int)
for record in misclassified[:200]:
    true_list = record['true_labels'] if isinstance(record['true_labels'], list) else [x.strip() for x in str(record['true_labels']).split(',')]
    pred_list = record['pred_labels'] if isinstance(record['pred_labels'], list) else [x.strip() for x in str(record['pred_labels']).split(',')]
    for td in true_list:
        if td in top8:
            ti = top8.index(td)
            if pred_list and pred_list[0] != 'No Finding':
                for pd_ in pred_list:
                    if pd_ in top8:
                        conf_matrix[ti][top8.index(pd_)] += 1
            else:
                conf_matrix[ti][ti] += 1

fig, ax = plt.subplots(figsize=(10, 8))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='YlOrRd', xticklabels=top8, yticklabels=top8, ax=ax, linewidths=0.5)
ax.set_title('Disease Confusion Matrix — Top 8 Diseases', fontsize=13, fontweight='bold')
ax.set_xlabel('Predicted / Missed (diagonal)')
ax.set_ylabel('True Label')
plt.xticks(rotation=30, ha='right')
plt.tight_layout()
plt.savefig('/content/confusion_matrix.png', dpi=120, bbox_inches='tight')
plt.show()
print('✅ Confusion matrix saved!')

# CELL 41 — Comprehensive pattern visualization
fig, axes = plt.subplots(2, 3, figsize=(20, 12))
fig.suptitle('Dataset-Level Error Pattern Analysis — Complete Overview', fontsize=14, fontweight='bold')

et_counts = llm_df['ERROR_TYPE'].value_counts()
axes[0][0].barh(et_counts.index[::-1], et_counts.values[::-1], color=plt.cm.Set2(np.linspace(0,1,len(et_counts))))
axes[0][0].set_title('Error Type Distribution', fontsize=11)
for i, v in enumerate(et_counts.values[::-1]):
    axes[0][0].text(v+0.3, i, str(v), va='center', fontsize=9)

fn_c2 = {}
for r in misclassified[:200]:
    for d in (r['false_negatives'] if isinstance(r['false_negatives'], list) else [x.strip() for x in str(r['false_negatives']).split(',')]):
        if d and d != 'None':
            fn_c2[d] = fn_c2.get(d, 0) + 1
top_fn = sorted(fn_c2.items(), key=lambda x: -x[1])[:10]
if top_fn:
    fn_n, fn_v = zip(*top_fn)
    axes[0][1].bar(fn_n, fn_v, color=plt.cm.Reds(np.linspace(0.4,0.9,len(fn_n))))
    axes[0][1].set_title('Top Missed Diseases (False Negatives)', fontsize=11)
    axes[0][1].tick_params(axis='x', rotation=40)

sev_c = llm_df['SEVERITY'].value_counts()
colors_sev = {'High':'#e74c3c','Medium':'#f39c12','Low':'#2ecc71'}
bars = axes[0][2].bar(sev_c.index, sev_c.values, color=[colors_sev.get(s,'gray') for s in sev_c.index])
axes[0][2].set_title('Clinical Severity Distribution', fontsize=11)
for bar in bars:
    axes[0][2].text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.5, str(int(bar.get_height())), ha='center', fontsize=10)

if disease_incons:
    sorted_di = sorted(disease_incons.items(), key=lambda x: -x[1])
    di_n, di_v = zip(*sorted_di)
    axes[1][0].barh(di_n[::-1], di_v[::-1], color=plt.cm.Oranges(np.linspace(0.4,0.9,len(di_n))))
    axes[1][0].set_title('Label Inconsistencies per Disease', fontsize=11)

if sorted_pairs:
    pl = [f'{a}\n↔{b}' for (a,b),_ in sorted_pairs[:6]]
    pv = [c for _,c in sorted_pairs[:6]]
    axes[1][1].bar(range(len(pl)), pv, color=plt.cm.Purples(np.linspace(0.4,0.9,len(pl))))
    axes[1][1].set_xticks(range(len(pl)))
    axes[1][1].set_xticklabels(pl, fontsize=7, rotation=20)
    axes[1][1].set_title('Top Confused Disease Pairs', fontsize=11)

sv = [int((llm_df['SEVERITY']==s).sum()) for s in ['High','Medium','Low']]
axes[1][2].pie(sv, labels=['High Severity','Medium Severity','Low Severity'],
               autopct='%1.1f%%', colors=['#e74c3c','#f39c12','#2ecc71'],
               startangle=90, pctdistance=0.75, wedgeprops=dict(width=0.5))
axes[1][2].set_title('Clinical Impact Summary', fontsize=11)

plt.tight_layout()
plt.savefig('/content/error_pattern_analysis.png', dpi=120, bbox_inches='tight')
plt.show()
print('✅ Error pattern analysis chart saved!')

import torch
import os

# Define the path to save the model in Google Drive
model_export_path = os.path.join(DRIVE_DIR, 'exported_cxr_model.pth')

# Save the model's state dictionary
torch.save(model.state_dict(), model_export_path)

print(f'✅ Model successfully exported to: {model_export_path}')

# CELL 42 — Global summary + save Block 9
error_summary = {
    'Total Test Samples'      : len(test_df),
    'Total Misclassified'     : len(misclassified),
    'Misclassification Rate'  : f'{100*len(misclassified)/len(test_df):.1f}%',
    'False Negatives'         : len([r for r in misclassified if r['false_negatives'] and r['false_negatives']!=['None']]),
    'Label Inconsistencies'   : int(incons_df['inconsistent'].sum()),
    'High Confidence Incons.' : int((incons_df['inconsistent'] & (incons_df['confidence']>=0.7)).sum()),
    'LLM Analyzed'            : len(llm_df),
    'High Severity Cases'     : int((llm_df['SEVERITY']=='High').sum()),
    'Bias Indicators Found'   : int(llm_df['BIAS_INDICATOR'].apply(lambda x: str(x).startswith('Yes')).sum()),
    'Most Confused Pair'      : f'{sorted_pairs[0][0][0]} ↔ {sorted_pairs[0][0][1]}' if sorted_pairs else 'N/A',
}

print('=' * 55)
print('GLOBAL ERROR TREND ANALYSIS')
print('=' * 55)
for k, v in error_summary.items():
    print(f'   {k:<35}: {v}')

import shutil
pd.DataFrame([error_summary]).to_csv('/content/error_pattern_summary.csv', index=False)
shutil.copy('/content/confusion_matrix.png',       f'{DRIVE_DIR}/confusion_matrix.png')
shutil.copy('/content/error_pattern_analysis.png', f'{DRIVE_DIR}/error_pattern_analysis.png')
shutil.copy('/content/error_pattern_summary.csv',  f'{DRIVE_DIR}/error_pattern_summary.csv')
print('\n✅ Block 9 complete and saved!')
print('   ➡️  Ready for Block 10 — Grad-CAM Visualization')

"""BLOCK 10 — Grad-CAM Explainability Visualization"""

# CELL 43 — Grad-CAM setup
from pytorch_grad_cam import GradCAM
from pytorch_grad_cam.utils.image import show_cam_on_image
from pytorch_grad_cam.utils.model_targets import ClassifierOutputTarget

def apply_gradcam(model, image_tensor, class_idx):
    target_layer  = model.features.denseblock4
    cam           = GradCAM(model=model, target_layers=[target_layer])
    targets       = [ClassifierOutputTarget(class_idx)]
    grayscale_cam = cam(input_tensor=image_tensor.unsqueeze(0).to(device), targets=targets)
    return grayscale_cam[0]

# Re-initialize the DenseNet121 model before loading weights
model = build_densenet121(num_classes=NUM_CLASSES).to(device)
model.load_state_dict(torch.load('/content/best_cxr_model.pth', map_location=device))
model.eval()
print('✅ Grad-CAM ready! Model loaded.')

# CELL 44 — Generate Grad-CAM for 4 error types
selected_samples = []
for etype in ['False Negative', 'Subtle Pathology Error', 'Overlapping Feature Confusion', 'False Positive']:
    subset = llm_df[llm_df['ERROR_TYPE'] == etype]
    if len(subset) > 0:
        selected_samples.append(subset.iloc[0])

while len(selected_samples) < 4:
    fn_s = llm_df[llm_df['ERROR_TYPE']=='False Negative']
    selected_samples.append(fn_s.iloc[len(selected_samples) % len(fn_s)])

fig, axes = plt.subplots(3, 4, figsize=(22, 16))
fig.suptitle('Grad-CAM Explainability — Misclassified Chest X-ray Samples\nRow 1: Original | Row 2: Grad-CAM (True Label) | Row 3: Grad-CAM (Predicted Label)',
             fontsize=13, fontweight='bold')

for col, sample in enumerate(selected_samples):
    image_id  = sample['image_id']
    true_str  = sample['true_labels']
    pred_str  = sample['pred_labels']
    etype     = sample['ERROR_TYPE']
    img_path  = os.path.join(IMAGE_DIR, image_id)

    raw_img   = Image.open(img_path).convert('RGB').resize((224, 224))
    rgb_array = np.array(raw_img).astype(np.float32) / 255.0
    img_tensor = val_test_transform(raw_img)

    true_list = [x.strip() for x in str(true_str).split(',') if x.strip() in DISEASE_LABELS]
    pred_list = [x.strip() for x in str(pred_str).split(',') if x.strip() in DISEASE_LABELS]
    true_idx  = DISEASE_LABELS.index(true_list[0]) if true_list else 0
    pred_idx  = DISEASE_LABELS.index(pred_list[0]) if pred_list else 0

    try:
        cam_true    = apply_gradcam(model, img_tensor, true_idx)
        overlay_true = show_cam_on_image(rgb_array, cam_true, use_rgb=True)
    except:
        overlay_true = (rgb_array * 255).astype(np.uint8)

    try:
        cam_pred    = apply_gradcam(model, img_tensor, pred_idx)
        overlay_pred = show_cam_on_image(rgb_array, cam_pred, use_rgb=True)
    except:
        overlay_pred = (rgb_array * 255).astype(np.uint8)

    axes[0][col].imshow(rgb_array)
    axes[0][col].set_title(f'Original\nTrue: {true_str[:25]}\nError: {etype}', fontsize=8)
    axes[0][col].axis('off')

    axes[1][col].imshow(overlay_true)
    axes[1][col].set_title(f'Grad-CAM → True Label\n"{true_list[0] if true_list else "N/A"}"\n(Where model SHOULD look)', fontsize=8, color='darkgreen')
    axes[1][col].axis('off')

    axes[2][col].imshow(overlay_pred)
    axes[2][col].set_title(f'Grad-CAM → Predicted\n"{pred_list[0] if pred_list else "No Finding"}"\n(Where model DID look)', fontsize=8, color='darkred')
    axes[2][col].axis('off')

plt.tight_layout()
plt.savefig('/content/gradcam_visualizations.png', dpi=130, bbox_inches='tight')
plt.show()
print('✅ Grad-CAM visualizations saved!')